name: main

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1

            - name: Install dependencies
              run: yarn

            - name: Compile and lint contracts
              run: |
                  yarn compile:contracts
                  yarn workspace @excubiae/contracts lint

            - name: Build packages
              run: yarn build:packages

            - name: Format
              run: yarn format:write

            - name: Run Eslint
              run: yarn lint:fix

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1

            - name: Install dependencies
              run: yarn

            - name: Build and Test contracts
              run: |
                  yarn compile:contracts
                  yarn test:contracts
